
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_CV(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,
	
	//////////// LED //////////
	input				  [9:0]		LED
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

    niosii_top u0 (
        .clk_1_clk       (CLOCK_50),       //   clk_1.clk
        .reset_1_reset_n (RESET_N),  // reset_1.reset_n
		  .pio_0_external_connection_export (LED)
    );

endmodule
